export const data = [
  {
    id: 1,
    name: 'Folder_1',
    type: 'folder',
    children: [
      {
        id: 2,
        name: 'Folder_1',
        type: 'folder',
        children: [],
      },
      {
        id: 3,
        name: 'Folder_2',
        type: 'folder',
        children: [
          {
            id: 4,
            name: 'File_1',
            type: 'file',
            size: '1.4kb',
            creation: '10-01-2021 10:10:30',
            last_update: '10-01-2021 10:10:30',
            author: 'Fabio',
          },
          {
            id: 5,
            name: 'File_2',
            type: 'file',
            size: '1.4kb',
            creation: '10-01-2021 10:10:30',
            last_update: '10-01-2021 10:10:30',
            author: 'Fabio',
          },
        ],
      },
    ],
  },
  {
    id: 6,
    name: 'Folder_2',
    type: 'folder',
    children: [],
  },
  {
    id: 7,
    name: 'Folder_3',
    type: 'folder',
    children: [],
  },
  {
    id: 8,
    name: 'Folder_4',
    type: 'folder',
    children: [
      {
        id: 9,
        name: 'Folder_1',
        type: 'folder',
        children: [],
      },
      {
        id: 10,
        name: 'Folder_2',
        type: 'folder',
        children: [
          {
            id: 11,
            name: 'File_1',
            type: 'file',
            size: '1.4kb',
            creation: '10-01-2021 10:10:30',
            last_update: '10-01-2021 10:10:30',
            author: 'Fabio',
          },
          {
            id: 12,
            name: 'File_2',
            type: 'file',
            size: '1.4kb',
            creation: '10-01-2021 10:10:30',
            last_update: '10-01-2021 10:10:30',
            author: 'Fabio',
          },
          {
            id: 8,
            name: 'Folder_4',
            type: 'folder',
            children: [
              {
                id: 9,
                name: 'Folder_1',
                type: 'folder',
                children: [
                  {
                    id: 8,
                    name: 'Folder_4',
                    type: 'folder',
                    children: [
                      {
                        id: 9,
                        name: 'Folder_1',
                        type: 'folder',
                        children: [],
                      },
                      {
                        id: 10,
                        name: 'Folder_2',
                        type: 'folder',
                        children: [
                          {
                            id: 11,
                            name: 'File_1',
                            type: 'file',
                            size: '1.4kb',
                            creation: '10-01-2021 10:10:30',
                            last_update: '10-01-2021 10:10:30',
                            author: 'Fabio',
                          },
                          {
                            id: 12,
                            name: 'File_2',
                            type: 'file',
                            size: '1.4kb',
                            creation: '10-01-2021 10:10:30',
                            last_update: '10-01-2021 10:10:30',
                            author: 'Fabio',
                          },
                        ],
                      },
                    ],
                  },
                ],
              },
              {
                id: 10,
                name: 'Folder_2',
                type: 'folder',
                children: [
                  {
                    id: 11,
                    name: 'File_1',
                    type: 'file',
                    size: '1.4kb',
                    creation: '10-01-2021 10:10:30',
                    last_update: '10-01-2021 10:10:30',
                    author: 'Fabio',
                  },
                  {
                    id: 12,
                    name: 'File_2',
                    type: 'file',
                    size: '1.4kb',
                    creation: '10-01-2021 10:10:30',
                    last_update: '10-01-2021 10:10:30',
                    author: 'Fabio',
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 13,
    name: 'Folder_5',
    type: 'folder',
    children: [],
  },
  {
    id: 14,
    name: 'Folder_6',
    type: 'folder',
    children: [],
  },
  {
    id: 15,
    name: 'File_1',
    type: 'file',
    size: '1.4kb',
    creation: '10-01-2021 10:10:30',
    last_update: '10-01-2021 10:10:30',
    author: 'Fabio',
  },
  {
    id: 16,
    name: 'File_2',
    type: 'file',
    size: '1.4kb',
    creation: '10-01-2021 10:10:30',
    last_update: '10-01-2021 10:10:30',
    author: 'Fabio',
  },
  {
    id: 17,
    name: 'File_1',
    type: 'file',
    size: '1.4kb',
    creation: '10-01-2021 10:10:30',
    last_update: '10-01-2021 10:10:30',
    author: 'Fabio',
  },
  {
    id: 18,
    name: 'File_2',
    type: 'file',
    size: '1.4kb',
    creation: '10-01-2021 10:10:30',
    last_update: '10-01-2021 10:10:30',
    author: 'Fabio',
  },
  {
    id: 19,
    name: 'File_1',
    type: 'file',
    size: '1.4kb',
    creation: '10-01-2021 10:10:30',
    last_update: '10-01-2021 10:10:30',
    author: 'Fabio',
  },
  {
    id: 20,
    name: 'File_2',
    type: 'file',
    size: '1.4kb',
    creation: '10-01-2021 10:10:30',
    last_update: '10-01-2021 10:10:30',
    author: 'Fabio',
  },
];
