name: 'UI Tests'

on: pull_request

jobs:
  # Run interaction and accessibility tests
  interaction-and-accessibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      ## install node and dependancies
      - uses: actions/setup-node@v4
        name: Setup Node.js
        with:
          node-version: '20.x'

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.6.6
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run linter
        run: pnpm run test:lint

      - name: Run formatter
        run: pnpm run test:prettier

      ### TODO: to fix ci running storybook tests ###
      # - name: Serve Storybook and run tests
      #   run: pnpm run serve:storybook:test

      - name: Install chromium
        run: pnpm playwright install chromium

      - name: Playwright component test
        run: pnpm test-ct
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
