name: 'UI Tests'

on:
  pull_request:
    branches:
      - dev
jobs:
  # Run interaction and accessibility tests
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run linter
        run: yarn run test:lint

  prettier:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Run formatter
        run: yarn run test:prettier

  interaction-and-accessibility:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Build Storybook
        run: yarn build-storybook --quiet

      - name: Serve Storybook and run tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "npx http-server storybook-static --port 6006 --silent" \
            "npx wait-on tcp:6006 && yarn test-storybook"
